# Exploratory Data Analysis of internal cfdna data
- samples provided by Comenius University Science Park

In [34]:
import pandas as pd
import os

In [35]:
base_path = "/data/projects/liquid_biopsy/Projects/cfDNA/cfDNA/"
path = "/data/projects/liquid_biopsy/Projects/cfDNA/cfDNA/data/source/internal/"
descriptions = pd.read_csv(path + "Onkologické vzorky - archív - Značenie.tsv", sep="\t")
dataset = pd.read_csv(path + "Onkologické vzorky - archív - Dataset.tsv", sep="\t")
cancer_types = pd.read_csv(path + "Onkologické vzorky - archív - Typ rakoviny.tsv", sep="\t")
material = pd.read_csv(path + "Onkologické vzorky - archív - Materiál.tsv", sep="\t")

In [36]:
descriptions['Dataset'].value_counts()

Dataset
Lynch populačná     501
Lynch CRC           227
Lynch rodiny         90
White Spring         23
MSI panel             4
Populačná EDTA        2
Populačná STRECK      1
Name: count, dtype: int64

In [37]:
ly_metadata = pd.read_csv(base_path + 'data/manifest/internal_metadata_ly.csv')
ly_metadata['cancer_true'].value_counts()

cancer_true
0    473
1    216
Name: count, dtype: int64

In [38]:
gs_metadata = pd.read_csv(base_path + 'data/manifest/internal_metadata_gs.csv')
gs_metadata['cancer_true'].value_counts()

cancer_true
0    19
1    19
Name: count, dtype: int64

In [39]:
gs_metadata

,sample_id,disease,dataset,material,frag_path,stage,cancer_true
0,gspp_ctr_00238_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00238_01_01_pl.GRCh37.frag.bed.gz,NaN,0
1,gsca_pca_00017_01_01_pl,pca,gsca,pl,frag/gsca_pca_00017_01_01_pl.GRCh37.frag.bed.gz,NaN,1
2,gspp_ctr_00019_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00019_01_01_pl.GRCh37.frag.bed.gz,NaN,0
3,gspp_ctr_00133_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00133_01_01_pl.GRCh37.frag.bed.gz,NaN,0
4,gsca_pca_00011_01_01_pl,pca,gsca,pl,frag/gsca_pca_00011_01_01_pl.GRCh37.frag.bed.gz,NaN,1
5,gsca_pca_00125_01_01_pl,pca,gsca,pl,frag/gsca_pca_00125_01_01_pl.GRCh37.frag.bed.gz,NaN,1
6,gspp_ctr_00300_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00300_01_01_pl.GRCh37.frag.bed.gz,NaN,0
7,gsca_pca_00009_01_01_pl,pca,gsca,pl,frag/gsca_pca_00009_01_01_pl.GRCh37.frag.bed.gz,NaN,1
8,gspp_ctr_00228_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00228_01_01_pl.GRCh37.frag.bed.gz,NaN,0
9,gsca_pca_00123_01_01_pl,pca,gsca,pl,frag/gsca_pca_00123_01_01_pl.GRCh37.frag.bed.gz,NaN,1
10,gspp_ctr_00251_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00251_01_01_pl.GRCh37.frag.bed.gz,NaN,0
11,gsca_pca_00001_01_01_pl,pca,gsca,pl,frag/gsca_pca_00001_01_01_pl.GRCh37.frag.bed.gz,NaN,1
12,gspp_ctr_00253_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00253_01_01_pl.GRCh37.frag.bed.gz,NaN,0
13,gsca_pca_00076_01_01_pl,pca,gsca,pl,frag/gsca_pca_00076_01_01_pl.GRCh37.frag.bed.gz,NaN,1
14,gsca_pca_00005_01_01_pl,pca,gsca,pl,frag/gsca_pca_00005_01_01_pl.GRCh37.frag.bed.gz,NaN,1
15,gspp_ctr_00152_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00152_01_01_pl.GRCh37.frag.bed.gz,NaN,0
16,gspp_ctr_00210_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00210_01_01_pl.GRCh37.frag.bed.gz,NaN,0
17,gspp_ctr_00037_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00037_01_01_pl.GRCh37.frag.bed.gz,NaN,0
18,gsca_pca_00164_01_01_pl,pca,gsca,pl,frag/gsca_pca_00164_01_01_pl.GRCh37.frag.bed.gz,NaN,1
19,gsca_pca_00103_01_01_pl,pca,gsca,pl,frag/gsca_pca_00103_01_01_pl.GRCh37.frag.bed.gz,NaN,1
20,gspp_ctr_00194_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00194_01_01_pl.GRCh37.frag.bed.gz,NaN,0
21,gspp_ctr_00288_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00288_01_01_pl.GRCh37.frag.bed.gz,NaN,0
22,gsca_pca_00163_01_01_pl,pca,gsca,pl,frag/gsca_pca_00163_01_01_pl.GRCh37.frag.bed.gz,NaN,1
23,gspp_ctr_00207_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00207_01_01_pl.GRCh37.frag.bed.gz,NaN,0
24,gspp_ctr_00106_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00106_01_01_pl.GRCh37.frag.bed.gz,NaN,0
25,gspp_ctr_00193_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00193_01_01_pl.GRCh37.frag.bed.gz,NaN,0
26,gspp_ctr_00248_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00248_01_01_pl.GRCh37.frag.bed.gz,NaN,0
27,gsca_pca_00012_01_01_pl,pca,gsca,pl,frag/gsca_pca_00012_01_01_pl.GRCh37.frag.bed.gz,NaN,1
28,gsca_pca_00016_01_01_pl,pca,gsca,pl,frag/gsca_pca_00016_01_01_pl.GRCh37.frag.bed.gz,NaN,1
29,gsca_pca_00014_01_01_pl,pca,gsca,pl,frag/gsca_pca_00014_01_01_pl.GRCh37.frag.bed.gz,NaN,1
30,gsca_pca_00061_01_01_pl,pca,gsca,pl,frag/gsca_pca_00061_01_01_pl.GRCh37.frag.bed.gz,NaN,1
31,gspp_ctr_00099_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00099_01_01_pl.GRCh37.frag.bed.gz,NaN,0
32,gspp_ctr_00301_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00301_01_01_pl.GRCh37.frag.bed.gz,NaN,0
33,gsca_pca_00008_01_01_pl,pca,gsca,pl,frag/gsca_pca_00008_01_01_pl.GRCh37.frag.bed.gz,NaN,1
34,gsca_pca_00004_01_01_pl,pca,gsca,pl,frag/gsca_pca_00004_01_01_pl.GRCh37.frag.bed.gz,NaN,1
35,gspp_ctr_00256_01_01_pl,ctr,gspp,pl,frag/gspp_ctr_00256_01_01_pl.GRCh37.frag.bed.gz,NaN,0
36,gsca_pca_00006_01_01_pl,pca,gsca,pl,frag/gsca_pca_00006_01_01_pl.GRCh37.frag.bed.gz,NaN,1
37,gsca_pca_00075_01_01_pl,pca,gsca,pl,frag/gsca_pca_00075_01_01_pl.GRCh37.frag.bed.gz,NaN,1

In [40]:
# sample_ids = ly_metadata['sample_id'].unique()
# dataset, typ, id, sample_order, replicate, material = zip(*[s.split('_') for s in sample_ids])
# sample_order = [int(i) for i in sample_order]
# replicate = [int(i) for i in replicate]
# ly_metadata['sample_order'] = sample_order
# ly_metadata['id'] = id
# ly_metadata['replicate'] = replicate
# samples_keep = ly_metadata.sort_values('sample_order').drop_duplicates('id', keep='last')['sample_id']
# ly_metadata_filtered = ly_metadata[ly_metadata['sample_id'].isin(samples_keep)]
# ly_metadata_filtered.shape
# ly_metadata_filtered = ly_metadata_filtered.drop(columns=['sample_order', 'replicate', 'id'])
# # ly_metadata_filtered.to_csv(base_path + 'data/manifest/internal_metadata_ly_filtered.csv', index=False)

In [41]:
# import random
# random.seed(1)
# ly_samples = pd.read_csv(base_path + 'data/manifest/internal_metadata_ly_filtered.csv')
# ly_samples = ly_samples['sample_id']
# # use 10% for testing
# test_samples = random.sample(list(ly_samples), int(0.2 * len(ly_samples)))
# train_samples = [s for s in ly_samples if s not in test_samples]
# test_metadata = ly_metadata_filtered[ly_metadata_filtered['sample_id'].isin(test_samples)]
# train_metadata = ly_metadata_filtered[ly_metadata_filtered['sample_id'].isin(train_samples)]
# test_metadata.to_csv(base_path + 'data/manifest/internal_metadata_ly_filtered_test.csv', index=False)
# train_metadata.to_csv(base_path + 'data/manifest/internal_metadata_ly_filtered_train.csv', index=False)

In [42]:
display(train_metadata['cancer_true'].value_counts())
display(test_metadata['cancer_true'].value_counts())

cancer_true
0    381
1     84
Name: count, dtype: int64

cancer_true
0    92
1    24
Name: count, dtype: int64

In [43]:
# # display(descriptions['Dataset'].value_counts())
# plasma_samples = descriptions[descriptions['Materiál'] == "Plazma"].reset_index(drop=True)
# print(plasma_samples['Dataset'].value_counts())
# # print(f'Number of unique patients: {plasma_samples["Pacient"].nunique()}')
# # print(plasma_samples['Poradie odberu'].value_counts())
# first_sampling = plasma_samples[plasma_samples['Poradie odberu'] == 2]
# # print(f'Number of unique patients with first sampling: {first_sampling["Pacient"].nunique()}')
# # print(first_sampling['Dataset'].value_counts())

In [44]:
# df_lynch_crc = plasma_samples[plasma_samples['Dataset'] == "Lynch CRC"].reset_index(drop=True)
# df_population_lynch = plasma_samples[plasma_samples['Dataset'] == "Lynch populačná"].reset_index(drop=True)
# # df_lynch_families = plasma_samples[plasma_samples['Dataset'] == "Lynch rodiny"].reset_index(drop=True)
# # df_population_edta = plasma_samples[plasma_samples['Dataset'] == "Populačná EDTA"].reset_index(drop=True)
# print(len(df_lynch_crc), len(df_population_lynch))

In [45]:
# df_lynch_crc['Sekvenačný beh'] = pd.to_datetime(df_lynch_crc['Sekvenačný beh'])

In [46]:
# df_lynch_crc.groupby(['Sekvenačný beh', 'Poradie odberu'])['Pacient'].unique()

In [47]:
# pozriet sa na gsca gspp tento groupby (datumy+ repliky)

# TODO feature motivy, snakemake - gsca gspp

In [53]:
ly_train = pd.read_csv(base_path + 'data/manifest/internal_metadata_ly_filtered_train.csv')
ly_test = pd.read_csv(base_path + 'data/manifest/internal_metadata_ly_filtered_test.csv')
gs = pd.read_csv(base_path + 'data/manifest/internal_metadata_gs.csv')
cristiano = pd.read_csv(base_path + 'data/manifest/Cristiano_metadata.csv')

for name, df in [('Lynch train', ly_train), ('Lynch test', ly_test), ('GS', gs), ('Cristiano', cristiano)]:
    print(f'=== {name} (n={len(df)}) ===')
    display(df['disease'].value_counts().to_frame('count'))

cristiano['cancer_true'].value_counts()

=== Lynch train (n=465) ===

         count
disease
ctr        381
crc         84

=== Lynch test (n=116) ===

         count
disease
ctr         92
crc         24

=== GS (n=38) ===

         count
disease
ctr         19
pca         19

=== Cristiano (n=459) ===

                   count
disease
Healthy              246
Breast cancer         53
Pancreatic cancer     35
Ovarian cancer        28
Colorectal cancer     27
Bile duct cancer      25
Gastric cancer        24
Lung cancer           20
Duodenal cancer        1

cancer_true
0    246
1    213
Name: count, dtype: int64